version: '2'

services:
  cfs1:
    container_name: cfs1
    image: cfs1
    restart: always
    ports:
      - "8080:8083"
    networks:
      extnetwork:
        ipv4_address: 192.168.0.14
  cfs2:
    container_name: cfs2
    image: cfs2
    restart: always
    ports:
      - "8081:8084"
    networks:
      extnetwork:
        ipv4_address: 192.168.0.15

  cfs3:
    container_name: cfs3
    image: cfs3
    restart: always
    ports:
      - "8082:8085"
    networks:
      extnetwork:
        ipv4_address: 192.168.0.16

networks:
  extnetwork:
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1